// Generated by gencpp from file uuv_gazebo_ros_plugins_msgs/GetThrusterState.msg
// DO NOT EDIT!


#ifndef UUV_GAZEBO_ROS_PLUGINS_MSGS_MESSAGE_GETTHRUSTERSTATE_H
#define UUV_GAZEBO_ROS_PLUGINS_MSGS_MESSAGE_GETTHRUSTERSTATE_H

#include <ros/service_traits.h>


#include <uuv_gazebo_ros_plugins_msgs/GetThrusterStateRequest.h>
#include <uuv_gazebo_ros_plugins_msgs/GetThrusterStateResponse.h>


namespace uuv_gazebo_ros_plugins_msgs
{

struct GetThrusterState
{

typedef GetThrusterStateRequest Request;
typedef GetThrusterStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetThrusterState
} // namespace uuv_gazebo_ros_plugins_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState > {
  static const char* value()
  {
    return "e2fdda8431274beee70eebaa081c813e";
  }

  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetThrusterState&) { return value(); }
};

template<>
struct DataType< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState > {
  static const char* value()
  {
    return "uuv_gazebo_ros_plugins_msgs/GetThrusterState";
  }

  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetThrusterState&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateRequest> should match 
// service_traits::MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState > 
template<>
struct MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState >::value();
  }
  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateRequest> should match 
// service_traits::DataType< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState > 
template<>
struct DataType< ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState >::value();
  }
  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateResponse> should match 
// service_traits::MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState > 
template<>
struct MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState >::value();
  }
  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateResponse> should match 
// service_traits::DataType< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState > 
template<>
struct DataType< ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_gazebo_ros_plugins_msgs::GetThrusterState >::value();
  }
  static const char* value(const ::uuv_gazebo_ros_plugins_msgs::GetThrusterStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_GAZEBO_ROS_PLUGINS_MSGS_MESSAGE_GETTHRUSTERSTATE_H
