// Generated by gencpp from file uuv_control_msgs/InitWaypointsFromFile.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MSGS_MESSAGE_INITWAYPOINTSFROMFILE_H
#define UUV_CONTROL_MSGS_MESSAGE_INITWAYPOINTSFROMFILE_H

#include <ros/service_traits.h>


#include <uuv_control_msgs/InitWaypointsFromFileRequest.h>
#include <uuv_control_msgs/InitWaypointsFromFileResponse.h>


namespace uuv_control_msgs
{

struct InitWaypointsFromFile
{

typedef InitWaypointsFromFileRequest Request;
typedef InitWaypointsFromFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitWaypointsFromFile
} // namespace uuv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_control_msgs::InitWaypointsFromFile > {
  static const char* value()
  {
    return "a0198a3f7b74ab5dc081e88db6d85c58";
  }

  static const char* value(const ::uuv_control_msgs::InitWaypointsFromFile&) { return value(); }
};

template<>
struct DataType< ::uuv_control_msgs::InitWaypointsFromFile > {
  static const char* value()
  {
    return "uuv_control_msgs/InitWaypointsFromFile";
  }

  static const char* value(const ::uuv_control_msgs::InitWaypointsFromFile&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_control_msgs::InitWaypointsFromFileRequest> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::InitWaypointsFromFile > 
template<>
struct MD5Sum< ::uuv_control_msgs::InitWaypointsFromFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::InitWaypointsFromFile >::value();
  }
  static const char* value(const ::uuv_control_msgs::InitWaypointsFromFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::InitWaypointsFromFileRequest> should match 
// service_traits::DataType< ::uuv_control_msgs::InitWaypointsFromFile > 
template<>
struct DataType< ::uuv_control_msgs::InitWaypointsFromFileRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::InitWaypointsFromFile >::value();
  }
  static const char* value(const ::uuv_control_msgs::InitWaypointsFromFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_control_msgs::InitWaypointsFromFileResponse> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::InitWaypointsFromFile > 
template<>
struct MD5Sum< ::uuv_control_msgs::InitWaypointsFromFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::InitWaypointsFromFile >::value();
  }
  static const char* value(const ::uuv_control_msgs::InitWaypointsFromFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::InitWaypointsFromFileResponse> should match 
// service_traits::DataType< ::uuv_control_msgs::InitWaypointsFromFile > 
template<>
struct DataType< ::uuv_control_msgs::InitWaypointsFromFileResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::InitWaypointsFromFile >::value();
  }
  static const char* value(const ::uuv_control_msgs::InitWaypointsFromFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_CONTROL_MSGS_MESSAGE_INITWAYPOINTSFROMFILE_H
