// Generated by gencpp from file uuv_control_msgs/IsRunningTrajectory.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MSGS_MESSAGE_ISRUNNINGTRAJECTORY_H
#define UUV_CONTROL_MSGS_MESSAGE_ISRUNNINGTRAJECTORY_H

#include <ros/service_traits.h>


#include <uuv_control_msgs/IsRunningTrajectoryRequest.h>
#include <uuv_control_msgs/IsRunningTrajectoryResponse.h>


namespace uuv_control_msgs
{

struct IsRunningTrajectory
{

typedef IsRunningTrajectoryRequest Request;
typedef IsRunningTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsRunningTrajectory
} // namespace uuv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_control_msgs::IsRunningTrajectory > {
  static const char* value()
  {
    return "7afca0099e0cddc25243b1e3569895fe";
  }

  static const char* value(const ::uuv_control_msgs::IsRunningTrajectory&) { return value(); }
};

template<>
struct DataType< ::uuv_control_msgs::IsRunningTrajectory > {
  static const char* value()
  {
    return "uuv_control_msgs/IsRunningTrajectory";
  }

  static const char* value(const ::uuv_control_msgs::IsRunningTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_control_msgs::IsRunningTrajectoryRequest> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::IsRunningTrajectory > 
template<>
struct MD5Sum< ::uuv_control_msgs::IsRunningTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::IsRunningTrajectory >::value();
  }
  static const char* value(const ::uuv_control_msgs::IsRunningTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::IsRunningTrajectoryRequest> should match 
// service_traits::DataType< ::uuv_control_msgs::IsRunningTrajectory > 
template<>
struct DataType< ::uuv_control_msgs::IsRunningTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::IsRunningTrajectory >::value();
  }
  static const char* value(const ::uuv_control_msgs::IsRunningTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_control_msgs::IsRunningTrajectoryResponse> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::IsRunningTrajectory > 
template<>
struct MD5Sum< ::uuv_control_msgs::IsRunningTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::IsRunningTrajectory >::value();
  }
  static const char* value(const ::uuv_control_msgs::IsRunningTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::IsRunningTrajectoryResponse> should match 
// service_traits::DataType< ::uuv_control_msgs::IsRunningTrajectory > 
template<>
struct DataType< ::uuv_control_msgs::IsRunningTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::IsRunningTrajectory >::value();
  }
  static const char* value(const ::uuv_control_msgs::IsRunningTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_CONTROL_MSGS_MESSAGE_ISRUNNINGTRAJECTORY_H
