// Generated by gencpp from file uuv_control_msgs/ResetController.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MSGS_MESSAGE_RESETCONTROLLER_H
#define UUV_CONTROL_MSGS_MESSAGE_RESETCONTROLLER_H

#include <ros/service_traits.h>


#include <uuv_control_msgs/ResetControllerRequest.h>
#include <uuv_control_msgs/ResetControllerResponse.h>


namespace uuv_control_msgs
{

struct ResetController
{

typedef ResetControllerRequest Request;
typedef ResetControllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetController
} // namespace uuv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_control_msgs::ResetController > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::uuv_control_msgs::ResetController&) { return value(); }
};

template<>
struct DataType< ::uuv_control_msgs::ResetController > {
  static const char* value()
  {
    return "uuv_control_msgs/ResetController";
  }

  static const char* value(const ::uuv_control_msgs::ResetController&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_control_msgs::ResetControllerRequest> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::ResetController > 
template<>
struct MD5Sum< ::uuv_control_msgs::ResetControllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::ResetController >::value();
  }
  static const char* value(const ::uuv_control_msgs::ResetControllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::ResetControllerRequest> should match 
// service_traits::DataType< ::uuv_control_msgs::ResetController > 
template<>
struct DataType< ::uuv_control_msgs::ResetControllerRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::ResetController >::value();
  }
  static const char* value(const ::uuv_control_msgs::ResetControllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_control_msgs::ResetControllerResponse> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::ResetController > 
template<>
struct MD5Sum< ::uuv_control_msgs::ResetControllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::ResetController >::value();
  }
  static const char* value(const ::uuv_control_msgs::ResetControllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::ResetControllerResponse> should match 
// service_traits::DataType< ::uuv_control_msgs::ResetController > 
template<>
struct DataType< ::uuv_control_msgs::ResetControllerResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::ResetController >::value();
  }
  static const char* value(const ::uuv_control_msgs::ResetControllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_CONTROL_MSGS_MESSAGE_RESETCONTROLLER_H
