// Generated by gencpp from file uuv_control_msgs/StartTrajectory.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MSGS_MESSAGE_STARTTRAJECTORY_H
#define UUV_CONTROL_MSGS_MESSAGE_STARTTRAJECTORY_H

#include <ros/service_traits.h>


#include <uuv_control_msgs/StartTrajectoryRequest.h>
#include <uuv_control_msgs/StartTrajectoryResponse.h>


namespace uuv_control_msgs
{

struct StartTrajectory
{

typedef StartTrajectoryRequest Request;
typedef StartTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartTrajectory
} // namespace uuv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_control_msgs::StartTrajectory > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::uuv_control_msgs::StartTrajectory&) { return value(); }
};

template<>
struct DataType< ::uuv_control_msgs::StartTrajectory > {
  static const char* value()
  {
    return "uuv_control_msgs/StartTrajectory";
  }

  static const char* value(const ::uuv_control_msgs::StartTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_control_msgs::StartTrajectoryRequest> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::StartTrajectory > 
template<>
struct MD5Sum< ::uuv_control_msgs::StartTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::StartTrajectory >::value();
  }
  static const char* value(const ::uuv_control_msgs::StartTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::StartTrajectoryRequest> should match 
// service_traits::DataType< ::uuv_control_msgs::StartTrajectory > 
template<>
struct DataType< ::uuv_control_msgs::StartTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::StartTrajectory >::value();
  }
  static const char* value(const ::uuv_control_msgs::StartTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_control_msgs::StartTrajectoryResponse> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::StartTrajectory > 
template<>
struct MD5Sum< ::uuv_control_msgs::StartTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::StartTrajectory >::value();
  }
  static const char* value(const ::uuv_control_msgs::StartTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::StartTrajectoryResponse> should match 
// service_traits::DataType< ::uuv_control_msgs::StartTrajectory > 
template<>
struct DataType< ::uuv_control_msgs::StartTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::StartTrajectory >::value();
  }
  static const char* value(const ::uuv_control_msgs::StartTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_CONTROL_MSGS_MESSAGE_STARTTRAJECTORY_H
