(cl:defpackage uuv_thruster_manager-srv
  (:use )
  (:export
   "GETTHRUSTERCURVE"
   "<GETTHRUSTERCURVE-REQUEST>"
   "GETTHRUSTERCURVE-REQUEST"
   "<GETTHRUSTERCURVE-RESPONSE>"
   "GETTHRUSTERCURVE-RESPONSE"
   "GETTHRUSTERMANAGERCONFIG"
   "<GETTHRUSTERMANAGERCONFIG-REQUEST>"
   "GETTHRUSTERMANAGERCONFIG-REQUEST"
   "<GETTHRUSTERMANAGERCONFIG-RESPONSE>"
   "GETTHRUSTERMANAGERCONFIG-RESPONSE"
   "SETTHRUSTERMANAGERCONFIG"
   "<SETTHRUSTERMANAGERCONFIG-REQUEST>"
   "SETTHRUSTERMANAGERCONFIG-REQUEST"
   "<SETTHRUSTERMANAGERCONFIG-RESPONSE>"
   "SETTHRUSTERMANAGERCONFIG-RESPONSE"
   "THRUSTERMANAGERINFO"
   "<THRUSTERMANAGERINFO-REQUEST>"
   "THRUSTERMANAGERINFO-REQUEST"
   "<THRUSTERMANAGERINFO-RESPONSE>"
   "THRUSTERMANAGERINFO-RESPONSE"
  ))

