(cl:defpackage uuv_manipulators_msgs-msg
  (:use )
  (:export
   "<ARMCONFIGCOMMAND>"
   "ARMCONFIGCOMMAND"
   "<ENDPOINTSTATE>"
   "ENDPOINTSTATE"
   "<ENDEFFECTORCOMMAND>"
   "ENDEFFECTORCOMMAND"
   "<ENDEFFECTORSTATE>"
   "ENDEFFECTORSTATE"
  ))

