// Generated by gencpp from file uuv_world_ros_plugins_msgs/GetOriginSphericalCoord.msg
// DO NOT EDIT!


#ifndef UUV_WORLD_ROS_PLUGINS_MSGS_MESSAGE_GETORIGINSPHERICALCOORD_H
#define UUV_WORLD_ROS_PLUGINS_MSGS_MESSAGE_GETORIGINSPHERICALCOORD_H

#include <ros/service_traits.h>


#include <uuv_world_ros_plugins_msgs/GetOriginSphericalCoordRequest.h>
#include <uuv_world_ros_plugins_msgs/GetOriginSphericalCoordResponse.h>


namespace uuv_world_ros_plugins_msgs
{

struct GetOriginSphericalCoord
{

typedef GetOriginSphericalCoordRequest Request;
typedef GetOriginSphericalCoordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetOriginSphericalCoord
} // namespace uuv_world_ros_plugins_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord > {
  static const char* value()
  {
    return "60457d630fe21cc5f8f6bd5d0fc90156";
  }

  static const char* value(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord&) { return value(); }
};

template<>
struct DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord > {
  static const char* value()
  {
    return "uuv_world_ros_plugins_msgs/GetOriginSphericalCoord";
  }

  static const char* value(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordRequest> should match 
// service_traits::MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord > 
template<>
struct MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord >::value();
  }
  static const char* value(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordRequest> should match 
// service_traits::DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord > 
template<>
struct DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord >::value();
  }
  static const char* value(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse> should match 
// service_traits::MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord > 
template<>
struct MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord >::value();
  }
  static const char* value(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse> should match 
// service_traits::DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord > 
template<>
struct DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoord >::value();
  }
  static const char* value(const ::uuv_world_ros_plugins_msgs::GetOriginSphericalCoordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_WORLD_ROS_PLUGINS_MSGS_MESSAGE_GETORIGINSPHERICALCOORD_H
