// Generated by gencpp from file uuv_sensor_plugins_ros_msgs/ChangeSensorState.msg
// DO NOT EDIT!


#ifndef UUV_SENSOR_PLUGINS_ROS_MSGS_MESSAGE_CHANGESENSORSTATE_H
#define UUV_SENSOR_PLUGINS_ROS_MSGS_MESSAGE_CHANGESENSORSTATE_H

#include <ros/service_traits.h>


#include <uuv_sensor_plugins_ros_msgs/ChangeSensorStateRequest.h>
#include <uuv_sensor_plugins_ros_msgs/ChangeSensorStateResponse.h>


namespace uuv_sensor_plugins_ros_msgs
{

struct ChangeSensorState
{

typedef ChangeSensorStateRequest Request;
typedef ChangeSensorStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeSensorState
} // namespace uuv_sensor_plugins_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState > {
  static const char* value()
  {
    return "d1c85d57f0ffdd55759c88fc35773fc9";
  }

  static const char* value(const ::uuv_sensor_plugins_ros_msgs::ChangeSensorState&) { return value(); }
};

template<>
struct DataType< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState > {
  static const char* value()
  {
    return "uuv_sensor_plugins_ros_msgs/ChangeSensorState";
  }

  static const char* value(const ::uuv_sensor_plugins_ros_msgs::ChangeSensorState&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateRequest> should match 
// service_traits::MD5Sum< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState > 
template<>
struct MD5Sum< ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState >::value();
  }
  static const char* value(const ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateRequest> should match 
// service_traits::DataType< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState > 
template<>
struct DataType< ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState >::value();
  }
  static const char* value(const ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateResponse> should match 
// service_traits::MD5Sum< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState > 
template<>
struct MD5Sum< ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState >::value();
  }
  static const char* value(const ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateResponse> should match 
// service_traits::DataType< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState > 
template<>
struct DataType< ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_sensor_plugins_ros_msgs::ChangeSensorState >::value();
  }
  static const char* value(const ::uuv_sensor_plugins_ros_msgs::ChangeSensorStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_SENSOR_PLUGINS_ROS_MSGS_MESSAGE_CHANGESENSORSTATE_H
