(cl:defpackage uuv_sensor_plugins_ros_msgs-msg
  (:use )
  (:export
   "<CHEMICALPARTICLECONCENTRATION>"
   "CHEMICALPARTICLECONCENTRATION"
   "<DVL>"
   "DVL"
   "<DVLBEAM>"
   "DVLBEAM"
   "<POSITIONWITHCOVARIANCE>"
   "POSITIONWITHCOVARIANCE"
   "<POSITIONWITHCOVARIANCESTAMPED>"
   "POSITIONWITHCOVARIANCESTAMPED"
   "<SALINITY>"
   "SALINITY"
  ))

