// Generated by gencpp from file uuv_manipulators_msgs/SolveIK.msg
// DO NOT EDIT!


#ifndef UUV_MANIPULATORS_MSGS_MESSAGE_SOLVEIK_H
#define UUV_MANIPULATORS_MSGS_MESSAGE_SOLVEIK_H

#include <ros/service_traits.h>


#include <uuv_manipulators_msgs/SolveIKRequest.h>
#include <uuv_manipulators_msgs/SolveIKResponse.h>


namespace uuv_manipulators_msgs
{

struct SolveIK
{

typedef SolveIKRequest Request;
typedef SolveIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveIK
} // namespace uuv_manipulators_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_manipulators_msgs::SolveIK > {
  static const char* value()
  {
    return "135cec71206c75b4d25a0c184fe860d8";
  }

  static const char* value(const ::uuv_manipulators_msgs::SolveIK&) { return value(); }
};

template<>
struct DataType< ::uuv_manipulators_msgs::SolveIK > {
  static const char* value()
  {
    return "uuv_manipulators_msgs/SolveIK";
  }

  static const char* value(const ::uuv_manipulators_msgs::SolveIK&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_manipulators_msgs::SolveIKRequest> should match 
// service_traits::MD5Sum< ::uuv_manipulators_msgs::SolveIK > 
template<>
struct MD5Sum< ::uuv_manipulators_msgs::SolveIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_manipulators_msgs::SolveIK >::value();
  }
  static const char* value(const ::uuv_manipulators_msgs::SolveIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_manipulators_msgs::SolveIKRequest> should match 
// service_traits::DataType< ::uuv_manipulators_msgs::SolveIK > 
template<>
struct DataType< ::uuv_manipulators_msgs::SolveIKRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_manipulators_msgs::SolveIK >::value();
  }
  static const char* value(const ::uuv_manipulators_msgs::SolveIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_manipulators_msgs::SolveIKResponse> should match 
// service_traits::MD5Sum< ::uuv_manipulators_msgs::SolveIK > 
template<>
struct MD5Sum< ::uuv_manipulators_msgs::SolveIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_manipulators_msgs::SolveIK >::value();
  }
  static const char* value(const ::uuv_manipulators_msgs::SolveIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_manipulators_msgs::SolveIKResponse> should match 
// service_traits::DataType< ::uuv_manipulators_msgs::SolveIK > 
template<>
struct DataType< ::uuv_manipulators_msgs::SolveIKResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_manipulators_msgs::SolveIK >::value();
  }
  static const char* value(const ::uuv_manipulators_msgs::SolveIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_MANIPULATORS_MSGS_MESSAGE_SOLVEIK_H
